### ISSUE TITLE
Creates too many mounts amd loop devices for a single entry. fbind -u not working.

### ISSUE THREAD

**Issue by thefzsalam** [Magisk-Modules-Repo/Magic-Folder-Binder#2]
![](https://i.imgur.com/WQneB0a.jpg)
![](https://i.imgur.com/NswskmE.jpg)
![](https://i.imgur.com/tmL2C15.jpg)
![](https://i.imgur.com/AazfEYM.jpg)

**Comment by VR-25** [comment]
Fixed, thanks!
