### ISSUE TITLE
About app_data

### ISSUE THREAD

**Issue by leenchan** [Magisk-Modules-Repo/Magic-Folder-Binder#3]
some apps ie. termius cant work. mounting was success. pls try it.

**Comment by leenchan** [comment]
after setenforce 0. it's ok. so i think all is about selinux

**Comment by VR-25** [comment]
You can add "setenforce 0" (unquoted) to config.txt and fbind will set SELinux mode to permissive automatically. If you're concerned about running in permissive at all times, try "setenforce auto" instead. This tells fbind to set SELinux mode to permissive before running its operations, and back to enforcing afterwards. If the mode was already permissive, it's left as is.
